# wrangler.toml - Cloudflare Pages project config
# 仅用于定义 D1/KV 绑定，Pages 构建使用 @cloudflare/next-on-pages

compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "funds-db"
database_id = "03c4d5de-597a-4e8b-a9a3-d4997594097f"

[[kv_namespaces]]
binding = "KV"
id = "c1c2704b96104d70abc787c66281dfa5"
